domain: NAM11 

GEM5:
        fst   : /pampa/poitras/DATA/GEM5/COSP2_NAM-11m_ERA5_GEM5_CLASS_NEWVEG_newP3-SCPF_SN_Lakes/Samples
        NetCDF: /pampa/poitras/DATA/GEM5/COSP2_NAM-11m_ERA5_GEM5_CLASS_NEWVEG_newP3-SCPF_SN_Lakes/Samples_NetCDF

CALIPSO:
        hdf   : /pampa/poitras/DATA/CALIPSO/CAL_LID_L2_05kmCPro-Standard-V4/hdf
        NetCDF: /pampa/poitras/DATA/CALIPSO/CAL_LID_L2_05kmCPro-Standard-V4/NetCDF
        list  : /pampa/poitras/DATA/CALIPSO/CAL_LID_L2_05kmCPro-Standard-V4/list

MODIS:
        hdf   : /pampa/poitras/DATA/MODIS/MXD06_L2/hdf    # MXD06 stands for MOD06, MYD06         # MXD06_L2 must be kept in the name
        NetCDF: /pampa/poitras/DATA/MODIS/MXD06_L2/NetCDF # MXD06 stands for MOD06, MYD06, MCD06  # MXD06_L2 must be kept in the name
        list  : /pampa/poitras/DATA/MODIS/MXD06_L2/list   # MXD06 stands for MOD06, MYD06, MCD06  # MXD06_L2 must be kept in the name

COSP2:   
        input : /pampa/poitras/DATA/COSP2/COSPIN/COSP2_NAM-11m_ERA5_GEM5_CLASS_NEWVEG_newP3-SCPF_SN_Lakes
        output: /pampa/poitras/DATA/COSP2/COSPOUT/COSP2_NAM-11m_ERA5_GEM5_CLASS_NEWVEG_newP3-SCPF_SN_Lakes
